"""Fix user-address relationship

Revision ID: 0231ef099f5a
Revises: 04ea9e6d0724
Create Date: 2025-08-02 23:52:53.144067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0231ef099f5a'
down_revision = '04ea9e6d0724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 