"""Fix user-address relationship

Revision ID: 04ea9e6d0724
Revises: d4db6a2339a9
Create Date: 2025-08-02 23:51:19.762902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ea9e6d0724'
down_revision = 'd4db6a2339a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 