"""Initial migration

Revision ID: 1e1cc692a00b
Revises: 2149ffec1a40
Create Date: 2025-08-09 17:14:53.937735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1cc692a00b'
down_revision = '2149ffec1a40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 