"""Fix user-address relationship

Revision ID: 2149ffec1a40
Revises: 0231ef099f5a
Create Date: 2025-08-02 23:57:34.662212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2149ffec1a40'
down_revision = '0231ef099f5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 