"""Add Address model and relationships to User and Donation

Revision ID: 32716f42eca6
Revises: 8d971f5848df
Create Date: 2025-08-02 23:33:43.405837

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, insert


# revision identifiers, used by Alembic.
revision = '32716f42eca6'
down_revision = '8d971f5848df'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # 1. Create addresses table
    op.create_table(
        'addresses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('street', sa.String(), nullable=False),
        sa.Column('city', sa.String(), nullable=False),
        sa.Column('state', sa.String(), nullable=True),
        sa.Column('postal_code', sa.String(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)

    # 2. Add address_id to donations (nullable at first)
    op.add_column('donations', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'donations', 'addresses', ['address_id'], ['id'])

    # 3. Add address_id to users (also nullable)
    op.add_column('users', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'addresses', ['address_id'], ['id'])

    # 4. Drop the old pickup_address column
    op.drop_column('donations', 'pickup_address')

    # 5. Insert a placeholder address
    op.execute(
        """
        INSERT INTO addresses (street, city, state, postal_code, country)
        VALUES ('Unknown', 'Unknown', NULL, NULL, 'Unknown')
        """
    )

    # 6. Assign placeholder address to existing donations
    op.execute("UPDATE donations SET address_id = 1")

    # 7. Finally, make donations.address_id NOT NULL
    op.alter_column('donations', 'address_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'address_id')
    op.add_column('donations', sa.Column('pickup_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_column('donations', 'address_id')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ### 