"""email column to users

Revision ID: 8d971f5848df
Revises: 74a855d1a79b
Create Date: 2025-08-02 11:11:49.782930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d971f5848df'
down_revision = '74a855d1a79b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 