"""Add Address model and relationships to User and Donation

Revision ID: c817caf59b64
Revises: 32716f42eca6
Create Date: 2025-08-02 23:49:04.201637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c817caf59b64'
down_revision = '32716f42eca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 