"""Fix user-address relationship

Revision ID: d4db6a2339a9
Revises: c817caf59b64
Create Date: 2025-08-02 23:51:07.169145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4db6a2339a9'
down_revision = 'c817caf59b64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 